#!/usr/bin/bash

hc() {
    herbstclient "$@"
}

hc pad 0 16 0 0 0

hc emit_hook reload

# autostart programs
/usr/bin/setroot /home/srsantos/.i3/wallpapers/herb.png
/usr/bin/xvisbell &
/usr/bin/xss-lock -- /usr/bin/i3lock -b -e -f -i /home/srsantos/.i3/wallpapers/herb.png &

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
# Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-e close_or_remove
hc keybind $Mod-Return spawn /usr/bin/termite
hc keybind $Mod-d spawn SSH_AUTH_SOCK=/run/user/1000/gnupg/S.gpg-agent.ssh /usr/bin/rofi -show run
hc keybind $Mod-Shift-n spawn /usr/bin/networkmanager_dmenu 

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-h       split   bottom  0.5
hc keybind $Mod-v       split   right   0.5

# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-s floating toggle
hc keybind $Mod-Shift-space floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# keybindings for locking screen
hc keybind $Mod-Control-l spawn /usr/local/bin/toggle_xautolock.sh
hc keybind $Mod-Shift-Control-l spawn /usr/bin/xset dpms force off

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# keybindings for hotkeys
hc keybind XF86AudioRaiseVolume spawn /usr/local/bin/pulseaudio-ctl_local up
hc keybind XF86AudioLowerVolume spawn /usr/local/bin/pulseaudio-ctl_local down
hc keybind XF86AudioMute spawn /usr/local/bin/pulseaudio-ctl_local mute
hc keybind XF86AudioMicMute spawn /usr/local/bin/pulseaudio-ctl_local mute-input
hc keybind XF86MonBrightnessUp spawn /usr/local/bin/brightness_indicator.sh up
hc keybind XF86MonBrightnessDown spawn /usr/local/bin/brightness_indicator.sh down
hc keybind XF86Display spawn /usr/bin/arandr
hc keybind XF86Search spawn /usr/bin/termite --title=glances -e "glances -1"
hc keybind XF86Tools spawn /usr/local/bin/touchpad_toggle.sh
hc keybind XF86Explorer spawn /usr/bin/lxappearance
hc keybind XF86LaunchA spawn /usr/bin/pulseaudio-equalizer-gtk
hc keybind Print spawn /usr/bin/scrot '%Y-%m-%d-%T_$wx$h_scrot.png' -e 'mv $f ~/Pictures/screenshots/'

# keybinding for browser
hc keybind $Mod-b spawn /usr/bin/xombrero

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#00CCCC'
hc set frame_border_normal_color '#396EB4'
hc set frame_bg_normal_color '#396EB4'
hc set frame_bg_active_color '#396EB4'
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 1
hc set frame_gap 4

hc attr theme.active.color '#396EB4'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color '#EF2929'
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 1
hc attr theme.floating.border_width 1
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#007F7F'
hc attr theme.active.outer_color '#396EB4'
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule class=Xombrero tag=5
hc rule class=mutt tag=6
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# tag rules

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# start tint2 and kill/restart on hlwm reload
#{
#pids=( )
# start the panel and remember its pid
#tint2 &
#pids+=( $! )
# wait until the panel should be stopped
#herbstclient -w '(quit_panel|reload)'
# stop all started panels
#kill ${pids[@]}
#} &

# start i3status and kill/restart on hlwm reload
#{
#pids=( )
# start the panel and remember its pid
#i3status -c ~/.config/i3status/dzen2/config | dzen2 -fn "PragmataPro:size=8" &
#pids+=( $! )
# wait until the panel should be stopped
#herbstclient -w '(quit_panel|reload)'
# stop all started panels
#kill ${pids[@]}
#} &

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
panel=~/bin/bar.sh
[ -x "$panel" ] || panel=/home/srsantos/.config/herbstluftwm/2panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done
